name: cloud.threefold.io
on:
  push:
    branches: [ master ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on cloud.threefold.io
      uses: appleboy/ssh-action@master
      with:
        host: cloud.threefold.io
        username: webuser
        key: ${{ secrets.TF_SECRET }}
        port: 34022
        script: |
          cd websites/www_tfcloud_zola/
          git log -1
          git fetch
          git reset --hard origin/master
          sed -i "s/https:\/\/www2.cloud.threefold.io/https:\/\/cloud.threefold.io/g" config.toml
          ./build.sh
