name: www2.cloud.threefold.io
on:
  push:
    branches: [ development ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on www2.cloud.threefold.io
      uses: appleboy/ssh-action@master
      with:
        host: www2.cloud.threefold.io
        username: webuser
        key: ${{ secrets.TF_SECRET }}
        port: 34022
        script: |
          cd websites/www2/www_tfcloud_zola/
          git log -1
          git fetch
          git reset --hard origin/development
          sed -i "s/https:\/\/cloud.threefold.io/https:\/\/www2.cloud.threefold.io/g" config.toml
          ./build.sh
